/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author KARINA
 */
public class MenuDetailLokasiGld extends javax.swing.JFrame {

    /**
     * Creates new form MenuDetailLokasiGld
     */
    public MenuDetailLokasiGld() {
        initComponents();
    }

    public JButton getButtonaddkel() {
        return buttonaddkel;
    }

    public JButton getButtonaddkuota() {
        return buttonaddkuota;
    }

    public JButton getButtonedit() {
        return buttonedit;
    }

    public JButton getButtoneditgeladi() {
        return buttoneditgeladi;
    }

    public JButton getButtonkurkuota() {
        return buttonkurkuota;
    }

    public JButton getButtonremovelokasi() {
        return buttonremovelokasi;
    }
    public void addListener(ActionListener a){
        buttonaddkuota.addActionListener(a);
        buttonaddkel.addActionListener(a);
        buttonedit.addActionListener(a);
        buttoneditgeladi.addActionListener(a);
        buttonkurkuota.addActionListener(a);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonedit = new javax.swing.JButton();
        buttonaddkuota = new javax.swing.JButton();
        buttonkurkuota = new javax.swing.JButton();
        buttonaddkel = new javax.swing.JButton();
        buttoneditgeladi = new javax.swing.JButton();
        buttonremovelokasi = new javax.swing.JButton();
        buttonback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Detail Geladi");

        buttonedit.setText("Edit Info Geladi");

        buttonaddkuota.setText("Tambah Kuota Geladi");
        buttonaddkuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonaddkuotaActionPerformed(evt);
            }
        });

        buttonkurkuota.setText("Kurangi Kuota Geladi");
        buttonkurkuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonkurkuotaActionPerformed(evt);
            }
        });

        buttonaddkel.setText("Tambah Kelompok");

        buttoneditgeladi.setText("Edit Kelompok Geladi");

        buttonremovelokasi.setText("Remove Lokasi Geladi");

        buttonback.setText("Kembali");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonedit, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonaddkuota)
                    .addComponent(buttonkurkuota, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttoneditgeladi, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonaddkel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonremovelokasi))
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(buttonback)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonaddkel)
                    .addComponent(buttonedit))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttoneditgeladi)
                    .addComponent(buttonaddkuota))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonremovelokasi)
                    .addComponent(buttonkurkuota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(buttonback)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonkurkuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonkurkuotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonkurkuotaActionPerformed

    private void buttonaddkuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonaddkuotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonaddkuotaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonaddkel;
    private javax.swing.JButton buttonaddkuota;
    private javax.swing.JButton buttonback;
    private javax.swing.JButton buttonedit;
    private javax.swing.JButton buttoneditgeladi;
    private javax.swing.JButton buttonkurkuota;
    private javax.swing.JButton buttonremovelokasi;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
