/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.awt.event.ActionListener;

import javax.swing.JButton;

/**
 *
 * @author JOKER
 */
public class MenuUtama extends javax.swing.JPanel {

    /**
     * Creates new form MainMenu
     */
    public MenuUtama() {
        initComponents();
    }

    public JButton getButtonmhs() {
        return buttonmhs;
    }

    public JButton getButtonpem() {
        return buttonpem;
    }

    public JButton getjButtonlogin() {
        return jButtonlogin;
    }

    public JButton getButtonkeluar() {
        return buttonkeluar;
    }
    
    public void addListener(ActionListener a){
        jButtonlogin.addActionListener(a);
        buttonpem.addActionListener(a);
        buttonmhs.addActionListener(a);
        buttonkeluar.addActionListener(a);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonlogin = new javax.swing.JButton();
        buttonmhs = new javax.swing.JButton();
        buttonpem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buttonkeluar = new javax.swing.JButton();

        jButtonlogin.setText("masuk dengan id");

        buttonmhs.setText("Daftar sebagai  mahasiswa");

        buttonpem.setText("Daftar sebagai pembimbing");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("SISFO GELADI");

        buttonkeluar.setText("Keluar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonmhs)
                    .addComponent(buttonpem))
                .addGap(157, 157, 157))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jButtonlogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(buttonkeluar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButtonlogin)
                .addGap(18, 18, 18)
                .addComponent(buttonmhs)
                .addGap(18, 18, 18)
                .addComponent(buttonpem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(buttonkeluar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonkeluar;
    private javax.swing.JButton buttonmhs;
    private javax.swing.JButton buttonpem;
    private javax.swing.JButton jButtonlogin;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
